### ISSUE TITLE
Soulbind items on certain actions

### ISSUE THREAD

**Issue by TfT-02** [TfT-02/Soulbound#12]
> I believe it could bind/rebind every time the player moves from chest to inventory, pickup, use, craft, on drop (Q key), and death. That should cover most ways. Even though it's a bit redundant, I think most servers can handle the load.
> 
> Possibly a "true/false" section in the config to pick which events the plugin should bind to customize and reduce unnecessary load
> 
> I apologize I don't actually know the names of these events.

```
Misc:
  Soulbound_On_Action:
    open_chest:
      - Diamond_Sword
    drop_item:
      - Diamond_Shovel
```

That will Soulbound those items to the player when he performs those actions.
