### ISSUE TITLE
Deleting items on death if "Prevent_Item_Drop: True"

### ISSUE THREAD

**Issue by keenerb** [TfT-02/Soulbound#42]
Cauldron 1.7.10, Soulbound v1.1.9.

This may just be my misunderstanding, but I believe it's a bug.

I've given the default group soulbound.items.keep_on_death' permission.  Initially everything worked fine, people would die and keep their soulbound items.  But, a few people managed to toss a soulbound whatever into lava or in the ocean and what have you, so I set 'Prevent_Item_Drop: true'

However, now when someone dies they simply lose their soulbound items.  All their soulbound items.

I don't know why that happens, but that's what I am seeing.

https://www.youtube.com/watch?v=KpTrxNL2Kb4&feature=youtu.be

Sorry for the horrible cropping job, but you can see where I bind a sign, try to drop it, and then it's lost when I /kill.

```

#
#  Soulbound configuration
#  Last updated on 1.1.9-b71
#
#####

#
#  Settings for Soulbound in general
###
General:
    # Allow Soulbound to report on basic anonymous usage
    Stats_Tracking: false

    # Allow Soulbound to check if a new version is available
    Update_Check: false
    Prefer_Beta: false

    # Should Soulbound print out debug messages?
    Verbose_Logging: true

    # Should Soulbound over-write configs to update, or make new ones ending in .new?
    Config_Update_Overwrite: true

Soulbound:
    Feedback_Messages_Enabled: true
    Prevent_Item_Drop: false
    Delete_On_Drop: false
    Allow_Item_Storing: true
    Infinite_Durability: false
    Blocked_Commands:
        /blockedcommand
    Commands_Bind_When_Used:
        /enchant

Dependency_Plugins:
    DiabloDrops:
        BindOnPickup: Legendary, Rare, Unidentified
        BindOnUse: Magical
        BindOnEquip: Set
    EpicBossRecoded:
        BindOnPickup: true
        BindOnUse: false
        BindOnEquip: false
    LoreLocks:
        Bind_Keys: true
    MythicDrops:
        BindOnPickup: common, uncommon, rare
        BindOnUse: terric, netheric
        BindOnEquip: endric
```
